services:
  story-downloader:
    image: ghcr.io/ammacdonald3/story-downloader:latest
    ports:
      - "5020:5000"
    volumes:
      - /mnt/watchtower_nfs_homes/appdata/stories/temp_upload:/story-downloader/app/data/epubs
      - /home/andrew/docker/story-downloader/logs:/story-downloader/app/data/logs
    restart: unless-stopped  # Automatically restart container unless manually stopped